### ISSUE TITLE
Add Data to Book Listing Table

### ISSUE THREAD

**Issue by tanishababic** [DispotoBrett/2020-fall-cs160-frozen-frogs#21]
Populate table with books

**Comment by DispotoBrett** [comment]
I don't think we want to go this route
Closing

**Comment by DispotoBrett** [comment]
Actually, we can use fixtures:
https://docs.djangoproject.com/en/3.1/howto/initial-data/

I'll write a few for demo purposes...  
as for shared photos... maybe ill use negative PKs for the books, then we won't have conflicts
